### ISSUE TITLE
Request: prebuilt binaries for Arm released on github

### ISSUE THREAD

**Issue by m040601** [mbrubeck/agate#1]
Hi, Matt. Thanks for your work on this package.
I'm no developer and quite new on this gemini cosmos.

I tested the binary you released.
Just to tell you, this is working fine on Arch Linux x64.
From all the other gemini servers I tested, this one gave me the less frills.Clear and concise instructions on the Readme page.
No problem with the SSL certificates.

I'm planning to make a package for Arch Linux x64. Both a Rust source package and a binary package (pulling from your binary release ).

Hope you can continue the good work, and releasing the binaries.
I have a request though.

> .... Agate.... should be quite efficient even when running on low-end hardware and serving many concurrent requests.

Exactly ! It was my guess also, and what attracted me to agate.
I'm just dying to test this on my Raspberry Pi's (both arm7h and aarch64). 

Very limited ressources for compiling.
Could you also release binaries for the arm platform ?
It would make it much easier for people who dont have, dont want to download the entire rust distribution to quickly try it out.

Thanks in advance

**Comment by mbrubeck** [comment]
Thanks a bunch for the interest!  I've uploaded ARM binaries for the latest release:

https://github.com/mbrubeck/agate/releases/tag/v1.2.2

I have only a Raspberry Pi Zero for testing, so the aarch64 and armv7 binaries are currently untested. Please let me know if they work for you!

**Comment by m040601** [comment]
Just to give you back feedback.

It's working great. I tested it on a Raspberry Pi 1.2.
Slow usage resources, everything looks fine.

Only thing I had to change was your SSL certificate instructions,

from


```
openssl req -x509 -newkey rsa:4096 -keyout key.rsa -out cert.pem \
    -days 3650 -nodes -subj "/CN=example.com"
```

to

```
openssl req -x509 -newkey rsa:4096 -keyout key.rsa -out cert.pem \
    -days 3650 -nodes -subj "/CN=localhost"
```


otherwise all gemini clients I tested, complained about the identity.
