### ISSUE TITLE
TLSv1.2 or TLSv1.3 ?

### ISSUE THREAD

**Issue by Ylhp** [mbrubeck/agate#12]
Hello there,

First, thanks for your work :) 

Is there a way with agate to specify which TLS version and even which ciphers we want to use within ? (ECDHE, etc.)

Ylph

**Comment by mbrubeck** [comment]
Currently, Agate always uses the default configuration of the [rustls](https://crates.io/crates/rustls) library, which allows TLS 1.2 and 1.3, with these ciphersuites:

    // TLS1.3 suites
    &TLS13_CHACHA20_POLY1305_SHA256,
    &TLS13_AES_256_GCM_SHA384,
    &TLS13_AES_128_GCM_SHA256,
    // TLS1.2 suites
    &TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
    &TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
    &TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
    &TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
    &TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
    &TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,

We could add options to change the TLS configuration, if necessary.  I’d be interested to know what use cases require this.

**Comment by Ylhp** [comment]
In my opinion, and as hoster, I've no regrets for forbiding access to my gemsite all those who don't want to use a not-so-recent security standard. Even more through Gemini.

I think it's overall a conceptual point of view : the cipher suites are (I guess) security ok obviously.

**Comment by Johann150** [comment]
So what you would want is a `--only-tls13` flag that makes Agate use only TLSv1.3?

**Comment by paper42** [comment]
The gemini specification says that only TLS 1.2 and TLS 1.3 (or only TLS 1.3) should be used, so agate shouldn't allow older versions.

**Comment by Johann150** [comment]
Yes, using TLS 1.2 and TLS 1.3 is the behaviour so far, you can see this if you look at the comment about the used cipher suites above. (Also the used TLS library does not even have support for TLS versions before 1.2)

I understand the specification like this:
* You MUST support TLS 1.2 and TLS 1.3.
* If you really want, you MAY drop support for TLS 1.2 (although I would not recommend this yet).

The logical step for me then would be to allow capsule admins to decide that they do not want to use TLS 1.2, by introducing the above flag.

**Comment by paper42** [comment]
You are right, I thought @Ylhp was saying that agate should optionally allow lower versions of TLS to make sure older devices work.
