### ISSUE TITLE
no logging with openrc 

### ISSUE THREAD

**Issue by fluxion-t** [mbrubeck/agate#135]
I am running agate (last version, compiled with cargo) in Alpine Linux (last version). 

The server works really well, and very fast. But I get no logging at all. 

My openrc script is

```
#!/sbin/openrc-run

command="/usr/sbin/agate"
command_args="--content /var/www/my_site/ --certs /etc/agate/certs/ --addr 192.168.1.12:1965 --hostname my.domain"
command_user="agate"
#command_background="yes"
command_background=true
pidfile="/run/$RC_SVCNAME/$RC_SVCNAME.pid"


start_pre() {
    checkpath --directory --owner $command_user:$command_user --mode 0775 \
    /run/$RC_SVCNAME
}

   

```

**Comment by Johann150** [comment]
First of all make sure you are looking in the right file. I don't know how openrc works, so sorry if thats a stupid question.

Maybe an environment variable for logging configuration is being set. You could try setting `RUST_LOG=agate` to enable all logging for agate.

**Comment by 06kellyjac** [comment]
https://wiki.gentoo.org/wiki/OpenRC#Logging do you need to turn on `rc_logger="YES"`?

do you have other openrc scripts that do output logs?
do they have to output to files? or is stdout/stderr enough?

**Comment by fluxion-t** [comment]
Johann150: My knowledge of openrc is also very limited, but Alpine Linux is so lightweight that I think it is worth the effort.  I haven't tried to set this environment variable, though. 

06kellyjac: I understand your link is to enable system logging, not Agate logging. Am I right?

Yes, I have other openrc scripts that do output logs, for example nginx.

stdout/stderr would be enough. And in that respect, I found something that enabled me to log them. I added the following to my previous script:

```
output_log="/var/log/agate/access.log"
error_log="/var/log/agate/error.log"
```

Weirdly, I get all the output in error.log, getting no stdout whatsoever. 

Before Agate, I had molly-brown set up for Gemini, but abandoned it after seeing its huge memory usage, and it was very slow compared to Agate. However, I managed to properly log with it with the following script (taken from the molly-brown page and tweaked after that)

```
#!/sbin/openrc-run
command="/usr/sbin/molly-brown"
command_user="gemini"
command_background="yes"
pidfile="/run/$RC_SVCNAME/$RC_SVCNAME.pid"


start_pre() {
    checkpath --directory --owner $command_user:$command_user --mode 0775 \
    /run/$RC_SVCNAME /var/log/molly
}
```

**Comment by Johann150** [comment]
> Weirdly, I get all the output in error.log, getting no stdout whatsoever.

From the documentation of `env_logger`:
> By default, env_logger writes logs to stderr, but can be configured to instead write them to stdout.

So it is to be expected that Agate logs everything to stderr. Note though, that the mentioned configuration would be in code. So not perfect, but since I would consider it a breaking change, I don't think this would be worth changing. I also had a look at `tools/freebsd/startup.sh` which seems to be redirecting both stdout and stderr to the same file, which makes me consider this even less of an issue.

Since you said your logging is working now, I'll close this issue. Please feel welcome to contribute your openrc script into the `tools` directory.
