### ISSUE TITLE
CI build for aarch64-apple-darwin

### ISSUE THREAD

**Issue by Suzie97** [mbrubeck/agate#137]
Is it possible to have a version of Agate that supports the new Apple Silicon?

Thanks

**Comment by Johann150** [comment]
As far as I can see, Rust itself does not yet support this: https://github.com/rust-lang/rust/issues/73908

**Comment by mbrubeck** [comment]
`aarch64-apple-darwin` is currently a tier-2 target.  We should be able to compile for this target using stable Rust, including cross-compiling from an `x86_64-apple-darwin` host.

**Comment by Johann150** [comment]
@Suzie97 could you test if this binary works: https://github.com/Johann150/agate/releases/tag/vtest

**Comment by Suzie97** [comment]
> @Suzie97 could you test if this binary works: https://github.com/Johann150/agate/releases/tag/vtest

Greattt! It works, nice work 👍🏼

**Comment by Johann150** [comment]
resolved by 2853ba5faf0d067fbb3957a9a6b959177df9656b
