### ISSUE TITLE
Doesn't listen in dual stack IPV4/IPV6 on FreeBSD

### ISSUE THREAD

**Issue by gegeweb** [mbrubeck/agate#14]
I'm running agate on FreeBSD 12.2.

It seems that it doesn't listen in dual stack IPV4/IPV6.

I you use `-addr 0.0.0.0:1965`that listen only on IPV4
I you use `-addr :::1965` that listen only on IPV6
I've tryed `-addr [::]:1965`, I thought it was working then in dual stack IPV4/IPV6 (tested under Linux, arm). Doesn't works on FreeBSD, that listen only on IPV6 too.
I'll retest on Linux…

I think, like gemeserv do, when using `[::]:`that should listen on both.

Actual workaround is running to instance of Agate, one listen on IPV4 and the second on IPV6.

**Comment by mbrubeck** [comment]
On my Linux system, `--addr :::1965` seems to bind to both IPv4 and IPv6 interfaces.

**Comment by Johann150** [comment]
On my `Debian 4.19.160-2 (2020-11-28)` server I can also observer what @gegeweb says. When I run agate with `--addr :::1965` and then `netstat -tlpv | grep agate` I only get this:
```
tcp6       0      0 [::]:1965               [::]:*                  LISTEN      3078/agate
```

But I wouldn't know how to resolve this easily because not every IPv6 address specified might be translatable into IPv4. (IIRC the other way around is always possible). As a possible solution I would suggest is that the default behaviour if no `--addr` option is supplied would change to listen to both `0.0.0.0:1965` and `:::1965`.

**Comment by gegeweb** [comment]
> On my Linux system, `--addr :::1965` seems to bind to both IPv4 and IPv6 interfaces.

On Linux yes (Raspberry Pi OS Buster), but not on FreeBSD, that listen only on IPV6.
On both system, agate is installed from git, tag 2.1.2 with `cargo build --release`. (Mmm… perhaps 2.1.1 on my FreeBSD)

@Johann150 I've the same result on Linux for the netsat command, but server reply with telnet on port 1965 on IPV4 and IPV6, and with a client only IPV4 works too.

I'll make more tests…

**Comment by gegeweb** [comment]
I confirm the behavior on FreeBSD with 2.1.2 (I was on 2.1.1).

`--addr :::1965` or `--addr [::]:1965` that listen only on IPV6.

```
# telnet localhost 1965
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
Trying ::1...
Connected to localhost.
Escape character is '^]'.
```

Workaround is always running two instances, one listening on IPV4 and second on IPV6.

**Comment by gegeweb** [comment]
There is the same issue with gemserv on FreeBSD, so that should come from one of the lbraries used.
But I can't help any more!

**Comment by gegeweb** [comment]
I found this:
https://github.com/stepancheg/rust-http2/issues/18, see also https://stackoverflow.com/questions/32051957/ipv6-why-are-ipv4-mapped-addresses-a-security-risk.
I thought it should be the same for all *BSD systems, so FreeBSD too.
And why it doesn't works for gemserv too.

**Comment by gegeweb** [comment]
For FreeBSD (don't know for OpenBSD or NetBSD):
```
sudo sysctl net.inet6.ip6.v6only=0
```
To keep it permanent, in `/etc/rc.conf`:
```
ipv6_ipv4mapping="YES"
```
See: https://www.freebsd.org/doc/handbook/network-ipv6.html#idp73225976

Thanks to Romain Tartière on the fediverse (https://mamot.fr/@smortex/105482398511582705).

Feel free to close this issue if you think it is not directly related to Agate. But as suggested by @Johann150 it should be a good thing to listen on both IPV4 and IPV6 without IPV4 mapping if no `--addr`specified.

**Comment by gegeweb** [comment]
As you can see here (in French) https://bsd.network/@solene/105491534090946437
OpenBSD have the same issue/behavior, but doesn't allow to enable IPV4 mapping as FreeBSD do.

**Comment by mbrubeck** [comment]
Agate 2.2.0 can now bind to multiple interfaces/addresses.  By default, it listens on both `0.0.0.0` and `::`.
