### ISSUE TITLE
"TLS error" error: tls handshake eof

### ISSUE THREAD

**Issue by LETRA** [mbrubeck/agate#167]
Hi, I am trying to run a Gemini pod on the subdomain gemini.letra.org.es. I've followed the instructions in a couple of tutorials https://landchad.net/gemini & gemini://sl1200.dystopic.world/art/noob.gmi and the github installation instructions, and repeated the process several times and I always get the same error.

The VPS is running Debian 11. The subdomain is created and operational. These are the error messages I get:

```
Started listener on 0.0.0.0:1965 
VPS_IP:1965 mI 00 "TLS error" error:tls handshake eof
```

![Captura de Pantalla 2022-04-08 a las 8 41 02](https://user-images.githubusercontent.com/16805254/162384158-6b55406a-d700-42e0-b4f2-8674defa1798.jpg)

```
WARN  agate] Could not start listener on 0.0.0.0:1965, but already listening on another unspecified 
address. Probably your system autlistening on another unspecified address. Probably your system 
automatically listens in dual stack?
```

![Captura de Pantalla 2022-04-08 a las 9 06 40](https://user-images.githubusercontent.com/16805254/162384165-1a780bf8-256f-4f3a-aa62-daddbad396de.jpg)

In Lagrange browser:

```
Untrusted Server Connection to the server was cancelled because its TLS certificate does not match the one we trust. Please check if the if server has announced a certificate change. If not, it is possible that a malicious third party is masquerading as the server you tried to reach.
The certificate can be marked as trusted in Page Information.
```

![Captura de Pantalla 2022-04-08 a las 8 41 19](https://user-images.githubusercontent.com/16805254/162384174-50f6ef35-52b7-4da0-ae98-65087a9b815a.jpg)

**Comment by Johann150** [comment]
From this I would assume that agate is working as intended, but your client (Lagrange) aborts the connection while it is being established ("handshake") for the reason it says:
> TLS certificate does mot match the one we trust.

It sounds like a different certificate was used for that domain before, which may lead to problems with Geminis TOFU (Trust On First Use) certificate validation scheme. If you follow the instructions the browser gives, you should be able to view the page.

**Comment by LETRA** [comment]
Thank you for your help. I should point out that the three messages are simultaneous. That is, we start from "TLS error" error:tls handshake eof

**Comment by Johann150** [comment]
That does not change the recommended action.

You can most likely safely ignore the 2nd message because most Linux based OS's will listen in dual stack these days, i.e. if you tell a server to listen on IPv6, it will also automatically listen on IPv4 as well, but Agate can not detect that apart from not being able to get the IPv4 port since it is already allocated to itself automatically.

And the 3rd message is just the client side of the 1st message.
