### ISSUE TITLE
+build prefix on latest release

### ISSUE THREAD

**Issue by 06kellyjac** [mbrubeck/agate#178]
o/

Just wondering what the `+build` prefix is at the end of the latest tag/release?
Will that be on all following tags/releases?

**Comment by Johann150** [comment]
The build pipeline failed because of a missing command, as can be seen in the commit log. The version is identical to the version without the suffix, as per semver 2.0.0 rule 10.

**Comment by 06kellyjac** [comment]
cool, thanks
