### ISSUE TITLE
Wrong Language Code for British English in the Documentation (README.md)

### ISSUE THREAD

**Issue by wanderer1988** [mbrubeck/agate#189]
I found that the README.md contains a wrong language code in the example of section "Meta Presets":
`index.gmi: ;lang=en-UK`

The IANA Region code for the United Kingdom is not "UK", but "GB" ("UK" is Ukraine). See [IANA Language subtag registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) (search for "Description: United Kingdom").

Resolution: Replace "en-UK" with "en-GB".

**Comment by Johann150** [comment]
I knew about this and still managed to mix them up. Thanks for reporting!
