### ISSUE TITLE
Prebuilt binary not working on a Raspberry Pi

### ISSUE THREAD

**Issue by mikekreuzer** [mbrubeck/agate#218]
The prebuilt agate.armv7-unknown-linux-gnueabihf binary didn't work on my Pi. Didn't do a thing.

It's only 1.8MB too, & my working build's 4.9MB, so... what's it, or what am I missing?

(Building from source works fine, thank you for making this! :smile:)

**Comment by Johann150** [comment]
I don't know which version of Raspberry Pi you are using. I can only tell you that it is working fine on my RPi 2B.

Regarding binary size, perhaps you didn't use the `--release` flag? In addition, the binaries built for release are run through [strip(1)](https://linux.die.net/man/1/strip) in the CI.

**Comment by mikekreuzer** [comment]
Yes 4.9MB for the release version, 54.2MB(!) for debug. Running `strip --strip-all` takes the release version down to 2.1MB, but it still works. I wonder if it'd still work on another model but I don't have anything different to test it on. This is on a Raspberry Pi 4 Model B Rev 1.2, with Agate being built on the Pi.

Feel free to close this issue if you want, it's more of an FYI. Like I said, building from source works fine.
