### ISSUE TITLE
"00 'TLS error' error:received corrupt message of type Handshake"

### ISSUE THREAD

**Issue by TB7836** [mbrubeck/agate#223]
I installed Agate 3.2.4 (from file agate.armv7-unknown-linux-gnueabihf.gz) on an offline test server running Raspberry Pi OS (Bullseye).  When I ran Agate for the first time, it created its own certificates in the ".certificates" directory.  When I tried to access my index.gmi page with Lagrange, it gave an error message saying, "TLS/SSL handshake failed", and at the same time Agate 3.2.4 said
```text
00 'TLS error' error:received corrupt message of type Handshake
```

When I tried with AV-98, it said
```text
DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
  context = ssl.SSLContext(protocol)
ERROR: [SSL: TLSV1_ALERT_ACCESS_DENIED] tlsv1 alert access denied (_ssl.c:997)
```
and Agate says:
```text
00 'TLS error' error:unexpected error: no server certificate chain resolved
```
 Agate obviously knows where the certificates are because it put them there.  What is going on?

**Comment by Johann150** [comment]
> no server certificate chain resolved

This may indicate no host name matched the installed certificates. Does the hostname you entered into the browser match the hostname you told agate?

**Comment by TB7836** [comment]
Since it is an offline test server, the name is just the IP address on my local network.  But even if I assign that IP address to the correct domain name using my /etc/resolv.conf file (and test that I did so correctly by going to that domain name in a web browser), the problem persists.

**Comment by Johann150** [comment]
I am not sure that I got you correctly. Could you please provide the following:
1. command that starts agate (with all parameters)
2. listing of everything beneath the certificate directory agate uses
3. URI that you requested

**Comment by Johann150** [comment]
closing this as stale
