### ISSUE TITLE
Certificate errors on laptop - not on mobile

### ISSUE THREAD

**Issue by pasdechance** [mbrubeck/agate#25]
Hello,

Great piece of software. Easy to use and quick too. I'm not a super experienced user but I have my pi running (following the same info here https://github.com/mbrubeck/agate/issues/1#issuecomment-701000475) and it works...but.

I can access the server from my mobile (with Ariane) but I cannot access the server with other devices in my home.

What could I be doing wrong?

I used this to generate a cert:

`openssl req -x509 -newkey rsa:4096 -keyout key.rsa -out cert.pem -days 3650 -nodes -subj "/CN=localhost"`

and I am running agate using defaults.

EDIT: I realised I explained nothing about the error

When I try to connect to the server from any other computer I receive this error:

```
Failed to connect to the server:                             
hostname does not verify: x509:                               
cannot validate certificate for xxx                              
xxx.x.xx because it doesn't contain                               
any IP SANs.
```

**Comment by mbrubeck** [comment]
> `openssl req -x509 -newkey rsa:4096 -keyout key.rsa -out cert.pem -days 3650 -nodes -subj "/CN=localhost"`

You should replace `localhost` with the hostname or IP address that you are using to access your server.

For example, if your server is accessible at `gemini://pi.example.com` then you should use `CN=pi.example.com`.

> I can access the server from my mobile (with Ariane) but I cannot access the server with other devices in my home.

I suspect this means that Ariane does not verify the hostname in the certificate, while your other clients do.

**Comment by pasdechance** [comment]
OK, looks like I had done it right the very first time, but not according to Amfora. It even loads through proxies...so thanks!
