### ISSUE TITLE
Running Gemini alongside the website with agate and Apache

### ISSUE THREAD

**Issue by nadrad** [mbrubeck/agate#26]
I hope my question is not too silly, but is it possible to install agate and have a Gemini capsule on the same server and for the same root domain that has a website with Apache? I prefer not to have a separate sub domain for Gemini, if possible.

**Comment by mbrubeck** [comment]
Yes.  You can simply run both programs on the same server, as long as they are using different ports.  Gemini servers use port 1965 by default, while web servers use ports 80 and 443 by default, so you shouldn't need to do anything special.
