### ISSUE TITLE
Can't run precompiled binary on Docker container that containes Alpine Linux

### ISSUE THREAD

**Issue by youshitsune** [mbrubeck/agate#270]
I've installed rust, rustup and cargo. But, the agate won't start. It throws this error:
```
thread 'main' panicked at 'range start index 1 out of range for slice of length 0', src/main.rs:244:31
```

You can recreate it by pulling docker image:
```
docker pull ghcr.io/youshitsune/gds:size_optimization
```

**Comment by mbrubeck** [comment]
It appears this is failing because `std::env::args()` is returning an empty list, while in a typical environment this list will have at least one element (`argv[0]`).

What happens if you pass at least one command-line argument to `agate`?

**Comment by mbrubeck** [comment]
The pre-compiled Linux binaries are all for GNU libc targets, so they will not work on platforms like Alpine Linux that use musl instead of glibc).  You will need to compile Agate from source for use on Alpine Linux.

**Comment by youshitsune** [comment]
Thank you!
