### ISSUE TITLE
Add ghcr.io Docker container generation to workflow actions

### ISSUE THREAD

**Issue by cortices** [mbrubeck/agate#279]
There's an open PR for improving the docker image size, which would be great to get merged.

But also it's difficult to deploy to any non-local server or kubernetes without a prebuilt image.

[This page from github support](https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-a-registry-using-a-personal-access-token) has pretty much a ready-to-go example for adding docker image generation to workflows. Until then I'll be having to copy images manually over ssh to my server, which is not ideal.

**Comment by Johann150** [comment]
As noted in https://github.com/mbrubeck/agate/pull/144#issuecomment-1110073345 I am still waiting for modifications to be made to that pull request. To clarify that I think that pull request is not complete I have marked it as a draft.

As noted in https://github.com/mbrubeck/agate/issues/145#issuecomment-1033561978 I am not knowledgeable in Docker. If you want the thing you mentioned, feel free to open a pull request.

**Comment by cortices** [comment]
Thanks for the info.
For what it's worth, I've used [@timwalls' Dockerfile](https://github.com/timwalls/agate/blob/master/Dockerfile) in the past and it's been great, but his repo is now several years behind this one. I am happy to provide a PR that merges his version's more canonical approach to copying source, with the same directory and calling conventions as this repo's one, so as to reduce the likelihood of a breaking change. I will look at what is needed to get github actions to compile the image too.
