### ISSUE TITLE
Support multiple --hostname's

### ISSUE THREAD

**Issue by ERnsTL** [mbrubeck/agate#28]
Greetings, please add support for multiple occurrences of --hostname

If would be nice to be able to limit responses only to ```domain.com```, ```gemini.domain.com``` and ```gmi.domain.com``` for example.

What do you think?

**Comment by Johann150** [comment]
🤔 Not sure what you mean. Do you mean these domains should access the same or different content?

If they should access the same content, you can just not use `--hostname`, which will assume the requested domain is the one this server is serving. Although in that case I would wonder why you want to have multiple domains for the same thing.

**Comment by dancojocaru2000** [comment]
Personally, I would like the ability to serve different files for different hostnames.

That way, if I have multiple domains pointing at the same server, I can have the same server serving different Gemini capsules.

This would probably mean either having the possibility to specify a content folder for each hostname or serving the content from a subfolder inside `--content` with the name of the hostname.

Example:
`gemini://a.com` => `/content/a.com/index.gmi`
`gemini://a.com/hello.gmi` => `/content/a.com/hello.gmi`
`gemini://b.com` => `/content/b.com/index.gmi`

**Comment by Johann150** [comment]
@dancojocaru2000 What you are looking for is called VHosts, and is not something Agate should implement seeing it is a "very simple Gemini server". I would recommend that you take a look at other software, e.g. [`gemserv`](https://git.sr.ht/~int80h/gemserv) which already has support for more advanced features like this.

**Comment by Johann150** [comment]
Maybe something like this?
***
### Virtual Hosts

Agate has support for a very simple version of virtual hosts. If you specify multiple `--hostname`s, Agate will look in the content root directory in a directory with the respective hostname.
For example if one hostname is `example.com`, the content directory is set to `./content` and `gemini://example.com/` is requested, Agate will look for files in `./content/example.com/`. This behaviour is only enabled if multiple `--hostname`s are specified.
Agate does not have support for multiple certificates, you will have to use a multi domain certificate.

**Comment by dancojocaru2000** [comment]
Something like that would be awesome!

**Comment by ERnsTL** [comment]
Thanks for adding this feature!

Upon trying it it out, agate produces a file not found error.

Using strace, it tries to access ```./content/index.gmi``` instead of ```./content/domain.xyz/index.gmi``` for some reason.

I am not sure how the path is built in depth, but it is either in parse_request() or send_response().

Adding a debug print in send_response() before the tokio file open, it really tries to open the ```./content/index.gmi```

**Comment by ERnsTL** [comment]
Multiple hostnames are given in the commandline.

**Comment by Johann150** [comment]
I cannot reproduce this. I tried: `agate --hostname example.com --hostname example.org`
```
./content
|-- example.com/
|   `-- index.gmi: "This is example.com\n=>gemini://example.org/"
`-- example.org/
    `-- index.gmi: "This is example.org\n=>gemini://example.com/"
```

Using a client that is modified to always connect to localhost, I can retrieve these files correctly.

What version/commit id are you using?

**Comment by ERnsTL** [comment]
Ah, my bad. Works.
