### ISSUE TITLE
Could not start listener on 0.0.0.0:1965, but already listening on another unspecified address

### ISSUE THREAD

**Issue by nicfab** [mbrubeck/agate#289]
I installed on Ubuntu 22.04.3 LTS `agate` via `cargo install agate`.
I set up `systemd`.
After running `systemctl status agate` I see:

`Could not start listener on 0.0.0.0:1965, but already listening on another unspecified address. Probably your system automatically listens in dual stack?`

How can I solve it?

**Comment by Johann150** [comment]
Note that at the start of the line before the message you pasted it says `WARN`. This signifies that this is a warning. It is not an error and thus does not need to be solved.

By default agate tries to listen on both IPv6 and IPv4 addresses. On some systems, listening on IPv6 will automatically also listen on IPv4, in which case this warning will show up. If you can reach your server using a gemini browser there should be nothing to worry about.

**Comment by SliderOnTheBlack** [comment]
hey, sorry about the necroposting but i'm having the same error but my site will not show up. whats happening?

**Comment by Johann150** [comment]
What command line options are you using when starting agate? Is there any other log output?

**Comment by SliderOnTheBlack** [comment]
im not using any options when starting and this is the output: 
./gemini.sh
[2024-01-10T07:02:49Z WARN  agate] Could not start listener on 0.0.0.0:1965, but already listening on another unspecified address. Probably your system automatically listens in dual stack?
[2024-01-10T07:02:49Z INFO  agate] Started listener on [::]:1965

**Comment by Johann150** [comment]
I don't know what `gemini.sh` is and how or with which command line options it calls `agate` so I'm still not sure what you are doing.

As above when originally closing this issue: The log output you have presented is just a warning, not an error. If the agate process does not quit, this should not be a problem.

Please check with `ss -tulpn` or `netstat -tulpn` whether there is a program listening on the respective port. If agate is listening on that port, maybe you need to check your firewall setup or something else.

**Comment by Johann150** [comment]
As before: I cannot mind read (yet) so if you are having issues please give a more detailed description of what you were doing exactly until the error happened. (e.g. version of agate used, what command line arguments you used)

(see also <https://github.com/mbrubeck/agate/blob/master/CONTRIBUTING.md#reporting-bugs-and-suggesting-improvements>)
