### ISSUE TITLE
The service is running, but browsers can't access the content

### ISSUE THREAD

**Issue by nadrad** [mbrubeck/agate#29]
I've just installed and set up agate. The output of `systemctl status agate` shows that the service is running, and I've opened port 1965 in the firewall. However, the capsule is not accessible yet (I/O timeout). Where should I look for problems? Are there logs anywhere other than in syslog? 

The traffic goes through Cloudflare; is it possible that it's causing a problem?

Thanks for the help!

**Comment by Johann150** [comment]
Not really an idea what it could be, I assume you are running the latest version `v2.4.1`? And did you use the systemd scripts in the `tools` directory, if you say you have checked `systemctl status agate`?

Something you could try is to access the server from a client on the same machine.

**Comment by nadrad** [comment]
Thanks Johann150. I followed your suggestion and checked it from the local machine, and it was working. The only thing I could think of was Cloudflare, and it was indeed the problem. 

In case someone else is reading this, has problems with their capsule, and wants to try it from the local machine, you may get an error because the certificate is probably set for the domain name and you're not using the domain name in the address. I added my domain name to /etc/hosts and mapped it to 127.0.0.1, and it solved the issue: I could test it on the local machine. 

Cloudflare was my DNS server and it was using its proxy. When I disabled its proxy for the A record of the domain (the DNS only option) my Gemini capsule worked. Although, then I had to install a separate SSL certificate for my website, and I couldn't do it because there was more than one website on my server. So, I built a new server for my domain and moved my website and capsule there.

I ran into a little trouble, but it was worth it. I really wanted my Gemini capsule to be on the root domain.

**Comment by mbrubeck** [comment]
Thanks for the update!
