### ISSUE TITLE
automated tests

### ISSUE THREAD

**Issue by Johann150** [mbrubeck/agate#34]
Today has shown that I am quite bad at testing in missing a quite glaring mistake. The question is how this would best be implemented so the tests can be run automatically, ideally with `cargo test` or alternatively by using a script etc.
things that should be tested include:

- [x] TLS connection can be established
- [x] restricted set of TLS versions is used for `-3` flag
- [x] content is delivered for files that are present
- [x] response header is set according to configuration
    - [x] globs are matched correctly
    - [x] configuration can be set for non-existent files
- [ ] correct configuration file is used depending on `-C` flag
- [x] secret files are hidden
    - [x] for non-existent files
    - [x] for existing files
    - [x] can be overridden by `--serve-secret`
- [x] hostname and port are checked when `--hostname` is supplied
- [ ] multiple hostnames work as documented

**Comment by 06kellyjac** [comment]
If you could add one or two tests to start with it'd help to see the format you'd like & where you want the tests written etc.

**Comment by Johann150** [comment]
I'm not sure how to make the tests since it would require starting agate and making requests to it with a gemini client. This probably rules out integrated Rust tests and would mean some kind of script. It would be nice if it could be run in GitHub's CI, i.e. on Ubuntu. If you have an idea, please make a PR.

**Comment by Johann150** [comment]
@06kellyjac I have now added a testing framework, some testing data and an exemplary test. Tests for the remaining test data still need to be added.
