### ISSUE TITLE
CGI scripts support ?

### ISSUE THREAD

**Issue by Eragonfr** [mbrubeck/agate#35]
Does Agate have a support of CGI scripts.
I think that it can be a good addition to the server.

**Comment by mbrubeck** [comment]
Currently, no. The current version of Agate only supports static files.

**Comment by Johann150** [comment]
I'm not sure if this would be a good addition or if this would complicate the code base a lot. After all this is supposed to be a "very simple Gemini server". I guess I am a bit wary of feature bloat.

**Comment by Johann150** [comment]
If you want to use CGI/SCGI I would recommend you use another server instead, as there are plenty. If you are looking for something in Rust, there is for example gemserv, see gemini://80h.dev/projects/gemserv

**Comment by aliceh75** [comment]
fwiw I consider the lack of CGI script as a feature, and one of the reasons I chose agate as my Gemini server :)

Gemini servers haven't been battle tested in the way that, say, Apache httpd or Nginx have. As such I much prefer a server that doesn't have the ability to execute scripts on my host machine.

**Comment by michaelnordmeyer** [comment]
For posterity, the above linked gemserv Rust Gemini server page is not reachable, but the canonical URL for the repo is [https://git.sr.ht/~int80h/gemserv/](https://git.sr.ht/~int80h/gemserv/).
