### ISSUE TITLE
Windows release artifact cannot be uncompressed

### ISSUE THREAD

**Issue by littleli** [mbrubeck/agate#36]
I wanted to run agate from my Windows box but I run into following issue:

```bash
Downloads $ gzip -d .\agate.x86_64-pc-windows-msvc.exe.gz

gzip.exe: .\agate.x86_64-pc-windows-msvc.exe.gz: not in gzip format
```

I also tried from WSL but it reports the same issue. Can you please validate if the artifact is ok? I have no comparison to anything that is working.

**Comment by littleli** [comment]
It seem that I can uncompress Mac or Linux artifacts can be uncompressed without issues on Windows box.

**Comment by Johann150** [comment]
I can also not uncompress it with `gzip -d` or `gunzip`, and it is also not a valid `.zip` file. I'll probably have to change the build pipeline and try to upload a build manually to the latest release.

**Comment by Johann150** [comment]
I have swapped the windows download on the release page for 2.5.2 to a zip file that only contains the exe file. The GitHub Action workflow has been adjusted so this should not happen again next time.
