### ISSUE TITLE
Proxy Request Refused with --hostname and portal.mozz.us

### ISSUE THREAD

**Issue by Sbgodin** [mbrubeck/agate#39]
Hi!

When I access my Gemini server, running with Agate installed some days ago, by a proxy server:
> portal.mozz.us/gemini/thesite.invalid

The website shows, as well as my log:
> 53 Proxy Request Refused

I run agate using:
> agate --content /var/…thesite.invalid --cert /etc/letsencrypt/live/thesite.invalid/cert.pem --key /etc/letsencrypt/live/thesite.invalid/privkey.pem --hostname thesite.invalid

The error disappears when I remove _--hostname thesite.invalid_.

**Comment by Johann150** [comment]
It would be helpful if you could give the respective log lines that show the response and - more importantly - the URL which was requested.

If the `--hostname` argument is given, Agate will start checking these things:
* The hostname in the request URL is one of the hostnames specified via the command line argument.
* The port in the URL is either not present or matches the port the request was received on.

**Comment by Sbgodin** [comment]
Got it. Thanks for the explanations, I used the `example.com` instead of `gmi.example.com`. As it works with HTTP (both addresses share the IP), I didn't expect it to fail.

Once I use `gmi.example.com` to access `gmi.example.com`, it works.

I was fooled by this proxy message, I didn't understand the situation. Thanks :-)
