### ISSUE TITLE
"" 00 "TLS error" error:unexpected error: incompatible signing key since update to v3.0.0

### ISSUE THREAD

**Issue by pasdechance** [mbrubeck/agate#42]
I updated my binary to v3.0.0 this morning (**armv7**)

Before updating I removed my old keys altogether, made a .certificates folder, and then ran:

`agate --content MYCONTENT/ --hostname HOSTNAME --lang en`

The new certs were created, and I can access it using Amfora, and on proxy.vulpes.one, but not on other proxies or client.

For example, when I try to access from Ariane on Android I get a **Handshake failed** error, and **Connection failed** errors on portal.mozz.us

The log returns:

```
[2021-03-27T14:03:58Z WARN  agate] [::ffff:192.168.1.57]:1965 - "" 00 "TLS error" error:peer is incompatible: no overlapping sigschemes

[2021-03-27T14:04:33Z WARN  agate] [::ffff:192.168.1.57]:1965 - "" 00 "TLS error" error:unexpected error: incompatible signing key
```

I started over from scratch this afternoon and end up with the same errors.

**Comment by Johann150** [comment]
If you generated new keys from scratch, you now have *Ed25519* keys (a specific cryptographic signing algorithm). These are known to cause problems with some libraries that have still not implemented support for them. Have a look at a mailing list thread about this if you are interested: <https://lists.orbitalfox.eu/archives/gemini/2021/006137.html>
If you want your certificates and thus your server to be more widely compatible with clients that do not implement Ed25519 (while again there is no reason to do so), you can try using the `--ecdsa` option. Reasons why you might not want to do that are outlined in the mail I linked.

Agate will not overwrite your existing certificate and key, so you have to move or delete them first if you want to generate different keys.

Can you try the option from above and see if that helps?

**Comment by pasdechance** [comment]
OK. Thanks for the quick answer. It appears to be working except for mobile clients and one of the proxies. I will leave it as is.

**Comment by pasdechance** [comment]
OK. Thanks for the quick answer. It appears to be working except for mobile clients and one of the proxies. I will leave it as is

**Comment by pasdechance** [comment]
Just wanted to add that, at least for me, the `--ecdsa` option is necessary for https://portal.mozz.us as well as mobile browsers like Ariane, Deedum, etc.

**Comment by kvibber** [comment]
Same here - I was unable to get any android browser to connect after upgrading to Agate 3.0.1 until I re-generated the keys with the --ecdsa option.
