### ISSUE TITLE
No such file: ".certificates" with version 3.0.0

### ISSUE THREAD

**Issue by steko** [mbrubeck/agate#44]
Hello, and thanks for creating+maintaining Agate!
I'm testing the latest release and the automatic certificate creation, but I get the following error:

```
./agate --content content --addr "[::]:1965" --addr 0.0.0.0:1965 --hostname gemini.iosa.it --lang it-IT
No such file: ".certificates"
```

If I manually create the directory, everything works well. But since the documentation doesn't mention the need to manually create the directory, it seems there's something missing either in the documentation itself or in the program.

**Comment by Johann150** [comment]
I see that is something I overlooked. Since the general theme is to take chores off of users, it would probably make the most sense to create the directory instead of changing the README.
