### ISSUE TITLE
Can't `cargo install agate`

### ISSUE THREAD

**Issue by lhp22** [mbrubeck/agate#46]
Hi,

I can't `cargo install agate`, I get an error message, I've put in verbose mode in the attached report file.
[cargo-install-agate-report.txt](https://github.com/mbrubeck/agate/files/6216231/cargo-install-agate-report.txt)

**Comment by Johann150** [comment]
🤔 I have tried that just fine right now while updating my own server. Are you using the latest Rust version?

**Comment by Johann150** [comment]
If you cannot give more information about your system, I cannot help you.
