### ISSUE TITLE
tlsv1 alert access denied

### ISSUE THREAD

**Issue by ricardoG08** [mbrubeck/agate#64]
hi, my agate server does not allow requests from sockets, it shows this message:

```
tlsv1 alert access denied
```

**Comment by Johann150** [comment]
Hmm, I do not know where this error could be coming from, probably from inside the TLS library. Since it says something about TLSv1, maybe make sure that you are using a TLS version >1.2

**Comment by ricardoG08** [comment]
I am using TLS version 1.2

**Comment by Johann150** [comment]
That should work too, unless of course you are using `--only-tls13`.

Sorry I don't think I can really help you with only this information. If you do find out more, feel free to comment again.

**Comment by ricardoG08** [comment]
problem solved, it was a problem with respect to the SNI.
