### ISSUE TITLE
Add directory listing

### ISSUE THREAD

**Issue by KillianKemps** [mbrubeck/agate#8]
When having a gemlog, it could be nice to be able to just link to a folder containing the articles and having the server serve the list of articles. 

Looking at the [Molly Brown server](https://tildegit.org/solderpunk/molly-brown), the feature can become quite complex. I think just allowing to display directories is enough. The users can sort the files by adding the date at the beginning of the filename for example.
For security reasons, maybe there should be a way to enable the directory listing per directory.

**Comment by Johann150** [comment]
The usually hidden files on Linux (i.e. files starting with a dot) should probably not be displayed. Then the listing could be enabled like in gitweb: If a file named e.g. `.directory-listing-ok` exists (its content does not matter, this is the "check file"), a directory listing is displayed if no `index.gmi` file exists.
1. Should this apply to subdirectories? (would probably bring performance penalties and may not be expected by users)
2. Should there be a command line option to allow listings in all directories?
3. Should the filename for the check file be configurable? (could be implemented as an optional value for 2.)

**Comment by mbrubeck** [comment]
Version 2.1.1 has some additional improvements to directory listings:

https://github.com/mbrubeck/agate/releases/tag/v2.1.1
