### ISSUE TITLE
serve multiple gemini capsules

### ISSUE THREAD

**Issue by satchlj** [mbrubeck/agate#91]
is it possible to serve multiple gemini capsules using agate? in all the tutorials and docs i've found it's assuming you just want to serve from one hostname. i have a vps and i want to serve several different gemini capsules for completely different purposes

**Comment by Johann150** [comment]
Yes it is possible, please refer to the [Virtual Hosts section of the Readme](https://github.com/mbrubeck/agate#virtual-hosts).

**Comment by satchlj** [comment]
thnx :) success!!
