### ISSUE TITLE
Directory Listing Customization?

### ISSUE THREAD

**Issue by joseph-marques** [mbrubeck/agate#98]
If it is in-line with the goals of the project as a simple gemini server, I think it would be a neat feature to add some sort of customization to the directory listing pages. Maybe allowing users to put gemtext in the .directory-listing-ok file and prepending that text to the generated listing? My main use case here would be to put a description of the folder and possiby include a link back to the root directory.

**Comment by Johann150** [comment]
Has been added with commit d10c5122531ac3e7297bd14834cb7bdcd46648ac.
